name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Check Docker Token Presence
        run: |
          if [ -n "${{ secrets.DOCKER_ACCESS_TOKEN }}" ]; then
            echo "Docker Access Token is set"
          else
            echo "Docker Access Token is not set"
          fi

      - name: Build DatabaseService Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/database-service:latest ./DatabaseService

      - name: Build PatientService Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/patient-service:latest ./PatientService

      - name: Build DoctorService Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/doctor-service:latest ./DoctorService

      - name: Push DatabaseService Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/database-service:latest

      - name: Push PatientService Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/patient-service:latest

      - name: Push DoctorService Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/doctor-service:latest