name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Check Docker Token Presence
        run: |
          if [ -n "${{ secrets.DOCKER_ACCESS_TOKEN }}" ]; then
            echo "Docker Access Token is set"
          else
            echo "Docker Access Token is not set"
          fi

      - name: Build and Push Docker Images
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push
